services:
  - type: web
    name: Abu-MD
    env: node
    branch: main
    repo: https://github.com/Aafx-Abu/Abu-MD.git
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
      - key: HANDLER
        value: ^
      - key: WORK_TYPE
        value: punlic
      - key: SERVER
        value: render
      - key: SUDO
        value: 917025994178
      - key: DATABASE_URL
        sync: false
