services:
  - type: web
    name: jarvis-md
    env: node
    branch: main
    repo: https://github.com/Loki-Xer/jarvis-md.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: HANDLER
        value: ^
      - key: WORK_TYPE
        value: punlic
      - key: SERVER
        value: render
      - key: SUDO
        value: 917025994178
      - key: DATABASE_URL
        sync: false
